config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resources :parks, only: [:new, :update, :edit]
  get '/parks', to: "static_pages#index"
  get '/parks/:id', to: "static_pages#index"

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :parks, only: [:index, :show, :create, :destroy] do
        resources :reviews, only: [:create, :destroy]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ApplicationRecord
  validates :name, presence: true
  validates :location, presence: true
  validates :description, presence: true
  mount_uploader :image, ImageUploader
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, presence: true, numericality: { only_integer: true, minimum: 1, maximum: 5 }
  validates :review_body, presence: true
  belongs_to :park
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :parks
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    role == "admin"
  end
end

app/controllers/api/v1/parks_controller.rb
class Api::V1::ParksController < ApiController

  def index
    if user_signed_in?
      render json: {
        parks: Park.all,
        scope: [current_user, user_signed_in?]
      }
    else
      render json: {
        parks: Park.all,
        scope: [id: 0]
      }
    end
  end

  def show
    park = Park.find(params[:id])
    binding.pry
    if user_signed_in?
      render json: {
        park: park,
        scope: [current_user, user_signed_in?],
        reviews: park.reviews
      }
    else
      render json: {
        park: park,
        reviews: park.reviews,
        scope: [id: 0]
      }
    end
  end

  def create
    binding.pry
    park = Park.new(park_params)
    park.user_id = current_user.id
    if park.save
      render json: {}
    else
      render json: {status: "error"}
    end
  end

  def destroy
    park_to_delete = Park.find(params[:id])
    park_to_delete.destroy

    render json: {
      parks: Park.all,
      scope: [current_user, user_signed_in?]
    }
  end

  private

  def park_params
    if params[:park][:image] == ""
      params.require(:park).permit(:name, :location, :description)
    else
      params.require(:park).permit(:name, :location, :description, :image)
    end
  end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApiController
  before_action :authenticate_user!
  def create
    review = Review.new(review_params)
    park = Park.find(params[:park_id])
    review.user_id = current_user.id
    
    if review.save
      render json: {
        park: park,
        reviews: park.reviews
      }
    else
      render json: {status: "error"}
    end
  end

  def destroy
    review_to_delete = Review.find(params[:id])
    review_to_delete.destroy
    park = Park.find(params[:park_id])

    if user_signed_in?
      render json: {
        park: park,
        reviews: park.reviews,
        scope: [current_user, user_signed_in?]
      }
    else
      render json: {
        park: park,
        reviews: park.reviews,
        scope: [id: 0]
      }
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :review_body, :park_id)
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :role])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def new
  end

  def edit
    @park = Park.find(params[:id])
  end

  def update
    @park = Park.find(params[:id])
    if @park.update(park_params)
      redirect_to park_path(@park)
    else
      flash.now[:message] = @park.errors.full_messages.to_sentence
      render :'parks/edit'
    end
  end

  private

  def park_params
    params.require(:park).permit(:name, :location, :description, :image)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NPReviews</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch|Delius|Lato|Staatliches&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/7fdd4b3628.js" crossorigin="anonymous"></script>
</head>
<body>

  <div class="top-bar-container" data-sticky-container>
    <nav class="sticky sticky-topbar" data-sticky data-options="anchor: page; marginTop:0" role="navigation">
      <div class="top-bar">

        <h1 class='top-bar title'>
          <%= link_to 'NATIONAL PARKS REVIEW', parks_path %>
        </h1>

        <section class="top-bar-section header">
          <ul class="menu">
            <li class="header-link">
              <%= link_to 'View All Parks', parks_path %>
            </li>
            <%- if current_user -%>
              <li class="header-link">
                <%= link_to 'Add a Park!', '/parks/new' %>
              </li>
              <li class="bar-button"><%= button_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <%- else -%>
              <li class="bar-button"><%= button_to 'Log In', new_user_session_path, method: :create %></li>
              <li class="bar-button"><%= button_to 'Sign Up', new_user_registration_path, method: :get %></li>
            <%- end -%>
          </ul>
        </section>
      </nav>
    </div>

  <div>
    <%- flash.each do |key, value| -%>
      <div class="flash-message flash flash-<%= key %>">
        <%= value %>
      </div>
    <%- end -%>
  </div>

  <div class="main">
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>

app/views/parks/edit.html.erb
<div class="form narrow-form">
  <h2 class="text-center">Park Edit Form</h2>

  <%= form_for @park do |f| %>
    <div class="field">
      <%= f.label :name%>
      <%= f.text_field :name %>
      <br />
    </div>

    <div class="field">
      <%= f.label :location%>
      <%= f.text_field :location %>
      <br />
    </div>

    <div class="field">
      <%= f.label :description%>
      <%= f.text_area :description %>
      <br />
    </div>

    <div class="field">
      <%= f.label :image, "Upload an image from your computer"%>
      <%= f.text_field :image %>
      <br />
    </div>

    <div class="auto-button">
      <%= f.submit "Edit Park" %>
      <br />
    </div>
  <%end%>

  <% if @form_error %>
    <%@form_error.each do |error| %>
      <p><%=error %></p>
    <%end%>
  <%end%>
</div>

app/views/parks/new.html.erb
<div id="app">
</div>

app/views/static_pages/index.html.erb
<div id="app">
</div>